AWSTemplateFormatVersion: "2010-09-09"
Resources: 
  lambdaIAMRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - "sts:AssumeRole"
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
      Policies:
        - PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - "lambda:InvokeFunction"
                  - "dynamodb:GetItem"
                  - "dynamodb:PutItem"
                  - "dynamodb:Query"
                  - "dynamodb:Scan"
                Effect: "Allow"
                Resource: '*'
          PolicyName: "lambdaIAMRole"
  getMediaRandom:
    Type: AWS::Lambda::Function
    DependsOn: lambdaIAMRole
    Properties:
      FunctionName: 'getMediaRandom'
      Runtime: nodejs12.x
      Role:
        "Fn::GetAtt": ["lambdaIAMRole", "Arn"]
      Handler: getMediaRandom.handler
      Code:
        S3Bucket: lambdas
        S3Key: getMediaRandom.zip
      Description: A lambda.
      TracingConfig:
        Mode: Active
